# Generated by Django 2.1.1 on 2018-09-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_one', '0002_auto_20180920_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('destination', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_created', models.ForeignKey(on_delete='models.CASCADE', related_name='job_created', to='app_one.User')),
                ('user_travelling', models.ManyToManyField(related_name='jobs_by_users', to='app_one.User')),
            ],
        ),
    ]
