# Generated by Django 2.1.1 on 2018-09-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='user_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
