# Generated by Django 2.1.1 on 2018-09-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handy_app', '0002_work_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='work',
            name='user_name',
        ),
    ]
